# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "base16-builder-go-${version}";
  version = "2019-06-15";
  rev = "cfaa6f1df06e0f913d6ecd5ce55c5d499ca1e0ad";

  goPackagePath = "github.com/belak/base16-builder-go";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/belak/base16-builder-go";
    sha256 = "06g3mbw8xxnk7jib9v65s190qicadg7xicpm131xdr82lgqr5qb2";
  };

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    description = "A simple builder for base16 color schemes";
    homepage = https://github.com/belak/base16-builder-go;
    license = licenses.mit;
    maintainers = [ maintainers.tadfisher ];
  };
}
