# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/Masterminds/vcs";
    fetch = {
      type = "git";
      url = "https://github.com/Masterminds/vcs";
      rev = "f94282d8632a0620f79f0c6ff0e82604e8c5c85b";
      sha256 = "15yvc80b1rj706fb8zl6acl4m4yv3p6r9j7pps1qa37wf98rbha5";
    };
  }
  {
    goPackagePath = "github.com/Sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/Sirupsen/logrus";
      rev = "07a84ee7412e7a28663d92930a1d46f81b124ee1";
      sha256 = "00hms8fnbhxb5lir3ykhl5lf1n2yqxddmd47cxp6d5ziv6k5swc8";
    };
  }
  {
    goPackagePath = "github.com/Unknwon/com";
    fetch = {
      type = "git";
      url = "https://github.com/Unknwon/com";
      rev = "0fed4efef7553eed2cd04624befccacda78bb8e2";
      sha256 = "1kd9wrz69cz01rb7csacrcg2dhydgbf18d6qn74wx2pfxxwnxdyx";
    };
  }
  {
    goPackagePath = "github.com/cbroglie/mustache";
    fetch = {
      type = "git";
      url = "https://github.com/cbroglie/mustache";
      rev = "73b1f3905474dd28d480fbb3f1da71b625a58e76";
      sha256 = "1l0ggygsf07ffmgv1lhhhqpiq041jl1r1dqri4gliddc863pzyrz";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "1c9c46d5c1cc2aaebdd1898c0680e85e8a44b36d";
      sha256 = "0mxliq4gfvdazga8mapc2sazi915rz1h6prnark9hwbbsz0xn0r3";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "24fa6976df40757dce6aea913e7b81ade90530e1";
      sha256 = "0rf6prz6gl0l1b3wijzdgq887cdwigvzxvz6gqbm5l8pkq3fx1m9";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "fae7ac547cb717d141c433a2a173315e216b64c4";
      sha256 = "11pl0dycm5d8ar7g1l1w5q2cx0lms8i15n8mxhilhkdd2xpmh8f0";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "51d6538a90f86fe93ac480b35f37b2be17fef232";
      sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa";
    };
  }
]
